### ISSUE TITLE
[Bug] Organization name not passing through for ugc posts

### ISSUE THREAD

**Issue by bthomson22** [fivetran/dbt_linkedin_pages_source#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The existing logic in the `stg_linkedin_pages__organization_ugc_post` model is only effective in parsing the `ugc_post_id` from `share` type posts. As a result, downstream models for `ugcpost` types having breaking joins. I noticed this when the `organization_name` came up as null for these types of posts.

The existing logic looks like:
`replace(ugc_post_id, 'urn:li:share:', '') as ugc_post_id`

Example output in `stg_linkedin_pages__organization_ugc_post`
![Screen Shot 2022-03-08 at 11 26 15 AM](https://user-images.githubusercontent.com/16456253/157301889-f96f3bdf-f7eb-4ea7-b572-f42f2312d7bc.png)

Example output in `linkedin_pages__post`:
![Screen Shot 2022-03-08 at 11 29 25 AM](https://user-images.githubusercontent.com/16456253/157302367-417cfaf0-667f-4123-8df7-e892aee4b3bb.png)

The logic is correct in `stg_linkedin_pages__ugc_post_history` since it considers both post types. As a result, the `ugc_post_id` looks right in `linkedin_pages__posts`, but the join with `organization_ugc_post` breaks due to mismatching `ugc_post_id`.

### Expected behavior

Proposed logic would look like:
`split_part(ugc_post_id, ':', -1) as ugc_post_id`

Example output of `stg_linkedin_pages__organization_ugc_post` with proposed fix:
![Screen Shot 2022-03-08 at 11 31 16 AM](https://user-images.githubusercontent.com/16456253/157302600-3757980b-e15e-48b1-9b4d-6e1dde725678.png)

Example output of `linkedin_pages__posts` with proposed fix:
![Screen Shot 2022-03-08 at 11 31 35 AM](https://user-images.githubusercontent.com/16456253/157302654-befeb71b-662d-4395-8bc3-02620c289a1a.png)

This will make the logic more dynamic, and effectively parse the `ugc_post_id` from both `share` and `ugcpost` types.

### dbt Project configurations

```
vars:
 
# Social Media Reporting
  social_media_rollup__linkedin_enabled: True

# LinkedIn Organic
  linkedin_pages_database: raw
  linkedin_pages_schema: fivetran_linkedin_organic

  
models:
  # disable both linkedin company pages models if not using linkedin company pages
  linkedin_pages:
      enabled: true
  linkedin_pages_source:
      enabled: true
```

### Package versions

```
  - package: fivetran/social_media_reporting
    version: [">=0.1.0", "<0.2.0"]
```

### What database are you using dbt with?

snowflake

### dbt Version
```
installed version: 1.0.3
   latest version: 1.0.3

Up to date!

Plugins:
  - snowflake: 1.0.0 - Up to date!
```

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
